"""ш

Revision ID: 47e6ac8de7f2
Revises: 
Create Date: 2025-04-08 21:36:09.530014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47e6ac8de7f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.alter_column('reservations', 'customer_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reservations', 'reservation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reservations', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_reservations_customer_name'), 'reservations', ['customer_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_customer_name'), table_name='reservations')
    op.alter_column('reservations', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reservations', 'reservation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('reservations', 'customer_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('reservations', 'end_time')
    # ### end Alembic commands ###
